### ISSUE TITLE
Ability to set spawn frequency for specific gens

### ISSUE THREAD

**Issue by Mumberthrax** [mickelus/customgen#1]
It would be nice to be able to set different spawn rates for different gens.

For example, say that I have a large dungeon I want to generate rarely, and I also have some totems or small aesthetic structures I want to generate more commonly in the world. At present, the only options I have are to set different rates for surface gens vs. underground vs. seafloor, so all gens on the surface generate at the same rate (assuming the same biomes).

**Comment by mickelus** [comment]
I'm looking into a second rewrite in which this will be included.
Until then it would be fairly easy to add the possibility to weight gens differently, would that work out for you?

**Comment by Mumberthrax** [comment]
Yes! That would be nice. :)

**Comment by mickelus** [comment]
This has been added in 70779b95e624a524f1626b4905e4a3a17b518823. I'm having some issues uploading to curseforge, until that's working it should be available here: http://mickelus.se/upl/customgen/customgen-R7-1.8.jar

**Comment by Mumberthrax** [comment]
Awesome!
